Document: qtmoko-ics2qtcal
Title: Debian qtmoko-ics2qtcal Manual
Author: <insert document author here>
Abstract: This manual describes what qtmoko-ics2qtcal is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qtmoko-ics2qtcal/qtmoko-ics2qtcal.sgml.gz

Format: postscript
Files: /usr/share/doc/qtmoko-ics2qtcal/qtmoko-ics2qtcal.ps.gz

Format: text
Files: /usr/share/doc/qtmoko-ics2qtcal/qtmoko-ics2qtcal.text.gz

Format: HTML
Index: /usr/share/doc/qtmoko-ics2qtcal/html/index.html
Files: /usr/share/doc/qtmoko-ics2qtcal/html/*.html
